dist: bonic
language: go
sudo: required
addons:
  apt:
    packages:
    - git
    - cmake
    - ccache
go:
  - "1.13.x"

branches:
  only:
  - master

before_install:
  - sudo apt-get update -q

install:
  - git clone https://github.com/shbta/encore
  - git clone https://github.com/ethereum/evmc
  - mkdir evmc/build
  - cd evmc/build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  - mkdir build

script:
  - cd build
  - cmake ..
  - make
  - sudo cp src/libathena.so /usr/local/lib
  - sudo ldconfig
  - cd ..
  - cd encore
  - go test -v -tags=evmc ./core/vm/runtime
